---
- name: Deploy Docker Container
  hosts: your_target_hosts
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Build Docker image
      docker_image:
        name: my-apache-container
        path: /path/to/dockerfile
        state: present

    - name: Run Docker container
      docker_container:
        name: my-apache-container
        image: my-apache-container
        state: started
        ports:
          - "80:80"

  handlers:
    - name: restart docker service
      service:
        name: docker
        state: restarted

